### ISSUE TITLE
Incompatible with Windows (x86/32-bit)

### ISSUE THREAD

**Issue by adsingh14** [jersou/markdown-explorer#1]
Hi !
After extracting the files, the setup shows incompatible dialog box on Windows 32-bit.

Windows App link : https://github.com/jersou/markdown-explorer/releases/download/v0.1.0/MarkdownExplorer-v0.1.0-Win32-x64.zip

**Comment by jersou** [comment]
Hi,
it's the 64 bits version, I just add the 32 bits zip : https://github.com/jersou/markdown-explorer/releases/download/v0.1.0/MarkdownExplorer-v0.1.0-win32-ia32.zip

**Comment by adsingh14** [comment]
Still not working, showing unspecified path error:
![Win32error](https://user-images.githubusercontent.com/35252877/37567102-fdc50216-2ae7-11e8-804f-98e27e7850a2.png)

**Comment by jersou** [comment]
Strange,
I don't have a 32 bits version, I only tested on a 64 bits version...
I will look later if I understand this error (and/or if I find a 32-bit version to reproduce)

**Comment by jersou** [comment]
I did a time travel, testing on a XP32 bit (VM), and I couldn't launch the app, but I didn't launch chromimum either, XP is probably to old to launch electon apps... I'can't reproduce on another Windows 32 bits version :-/

I have tried to rebuild the app from node/electron 32 bits, but the result files are the same (https://github.com/electron-userland/electron-packager/issues/713).

However, your error message looks like a permission problem, do you run the app with an admin user ?

**Comment by adsingh14** [comment]
I'm using **Windows 7 Ultimate SP1** (Up-to-date).

I've already tested it in administrative mode. Nothing worked.

**Comment by jersou** [comment]
I checked on a fresh installation of windows 7 32 bits and it works fine : 
![win7-32](https://user-images.githubusercontent.com/5874319/37592541-47796a64-2b6f-11e8-9a47-5401de75d3e0.png)
