### ISSUE TITLE
logo design for markdown-explorer application

### ISSUE THREAD

**Issue by harunbadilli** [jersou/markdown-explorer#2]
Hi there, I designed a logo for markdown-explorer application. I hope you will like it. In case you like, I can send the logo files in the format you want. You can choose whatever you like in black and white.
![1](https://user-images.githubusercontent.com/34319922/37670579-b77cacf2-2c7a-11e8-8dcd-ad77e34fe9d2.png)
![2](https://user-images.githubusercontent.com/34319922/37670595-beddcddc-2c7a-11e8-92c1-794539319d5b.png)
![3](https://user-images.githubusercontent.com/34319922/37670602-c31e47f0-2c7a-11e8-9416-cf046082d0fc.png)
![4](https://user-images.githubusercontent.com/34319922/37670606-c5f16f84-2c7a-11e8-90d9-d5f56da9e2ed.png)

**Comment by jersou** [comment]
Thanks, but even if I'm not satisfied with the logo I created, I prefer it to your proposal.

The current logo has a meaning :
* "Mardown" is usually abbreviated to "md", the magnifying glass is oriented to make a "d".
* The "E" of "explorer" has the shape of a tree structure (too small, probably).
* The blur on the "M" and "d" is present to highlight the "Explorer" (awkwardly, probably)

In addition : cf. https://steemit.com/utopian-io/@harunbadilli/wifianalyzer-logo-design
The wifi symbol has just been replaced by an "M" to create your "Markdown-Explorer" proposal logo.
![screenshot148](https://user-images.githubusercontent.com/5874319/37686682-c3f6f41a-2c98-11e8-8b59-11bb5878fea8.png)

[github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/158](https://github.com/VREMSoftwareDevelopment/WiFiAnalyzer/issues/158) ?

Thanks anyway :-).
