### ISSUE TITLE
Image display issues when editing files

### ISSUE THREAD

**Issue by AlexGStapleton** [jersou/markdown-explorer#3]
Preface: Really good work on your first big app! 👍 

I've been tasked with rewriting certain elements of our [developer documentation](https://github.com/siteorigin/docs) so I was looking for a markdown writer to help with that and found your software. It appears as though images aren't currently displayed/working _when_ edting a file - they are visible in the inittial preview. For example, if I load [our docs](https://github.com/siteorigin/docs) into your software, the [Widget Bundles image directory](https://github.com/siteorigin/docs/tree/develop/widgets-bundle/images) (or are any) aren't included. This makes working with pages are are somewhat image heavy (such as the [form fields page](https://github.com/siteorigin/docs/blob/develop/widgets-bundle/form-building/form-fields.md)) tricky as there's no way of knowing if the image was included correctly.

For reference, here's a screenshot of what I see when editing the Form Fields page:

![](https://vgy.me/3Yg0cu.png)

Notice the broken images on the right

**Comment by jersou** [comment]
Thanks for the report.
It's fixed in the v0.1.1 release.
