### ISSUE TITLE
Vulnerability report

### ISSUE THREAD

**Issue by silviavali** [jersou/markdown-explorer#4]
Hello

I would like to report a vulnerability in the markdown explorer. Could you contact me please at silviavali14@gmail.com

Best, 
Silvia

**Comment by silviavali** [comment]
Why would you close this ticket if it is unresolved?

**Comment by jersou** [comment]
If you have information, write it here... or at markdown-explorer@soulary.com
I didn't think your message was serious issue (a spam), like #2 ...

If your report is the same as the github automatic vulnerability detection (from package.json dependencies) : I have seen them, and fix them, except for the bootstrap 3.3.7 (no fix with the v3 at the moment).

Regards
Jeremy
