### ISSUE TITLE
Relative links for local files

### ISSUE THREAD

**Issue by LucaBernstein** [jersou/markdown-explorer#6]
At the moment when creating relative links ME cannot resolve it:

Folder structure:
![image](https://user-images.githubusercontent.com/16018720/40046267-d5012590-582c-11e8-9292-4d205a9cee97.png)

File content of Readme.md: `[Knowledge](Knowledge/)`

But right clicking - copy link shows rendered path: `file:///C:/Users/YourUserAccount/Documents/_Personal/PortableApplications_Installed/MarkdownExplorer-v0.1.0-Win32-x64/MarkdownExplorer-v0.1.0-Win32-x64/resources/app.asar/app/MarkdownExplorer/Knowledge/`

I would expect to be directed to specified folder.
Opening in new window might only be useful if poining to file. But I guess this is also not working perfectly since relative, local links seem not to work.

Thanks in advance and with kind regards,

Luca

**Comment by jersou** [comment]
Thank for the report.

Currently, relative links only work for files, not for folders.
`[Knowledge](Knowledge/)` doesn't work, but `[Knowledge](Knowledge/base.md)` will if "Knowledge/base.md" exists.

I suppose ME could detect the first file in the folder and display it, but it's not currently handled, such as the opening of a new window.

regards
Jeremy
